// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/private_kvs.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/averak/hbaas/protobuf/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PrivateKVSServiceName is the fully-qualified name of the PrivateKVSService service.
	PrivateKVSServiceName = "api.PrivateKVSService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PrivateKVSServiceGetETagV1Procedure is the fully-qualified name of the PrivateKVSService's
	// GetETagV1 RPC.
	PrivateKVSServiceGetETagV1Procedure = "/api.PrivateKVSService/GetETagV1"
	// PrivateKVSServiceGetV1Procedure is the fully-qualified name of the PrivateKVSService's GetV1 RPC.
	PrivateKVSServiceGetV1Procedure = "/api.PrivateKVSService/GetV1"
	// PrivateKVSServiceSetV1Procedure is the fully-qualified name of the PrivateKVSService's SetV1 RPC.
	PrivateKVSServiceSetV1Procedure = "/api.PrivateKVSService/SetV1"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	privateKVSServiceServiceDescriptor         = api.File_api_private_kvs_proto.Services().ByName("PrivateKVSService")
	privateKVSServiceGetETagV1MethodDescriptor = privateKVSServiceServiceDescriptor.Methods().ByName("GetETagV1")
	privateKVSServiceGetV1MethodDescriptor     = privateKVSServiceServiceDescriptor.Methods().ByName("GetV1")
	privateKVSServiceSetV1MethodDescriptor     = privateKVSServiceServiceDescriptor.Methods().ByName("SetV1")
)

// PrivateKVSServiceClient is a client for the api.PrivateKVSService service.
type PrivateKVSServiceClient interface {
	GetETagV1(context.Context, *connect.Request[api.PrivateKVSServiceGetETagV1Request]) (*connect.Response[api.PrivateKVSServiceGetETagV1Response], error)
	// KVS のエントリを検索します。
	// ただし、検索条件が空の場合は空リストを返します。
	GetV1(context.Context, *connect.Request[api.PrivateKVSServiceGetV1Request]) (*connect.Response[api.PrivateKVSServiceGetV1Response], error)
	// KVS にエントリを登録します。
	// エントリの作成、更新、削除を行うことが可能で、value が空のエントリは削除されます。
	SetV1(context.Context, *connect.Request[api.PrivateKVSServiceSetV1Request]) (*connect.Response[api.PrivateKVSServiceSetV1Response], error)
}

// NewPrivateKVSServiceClient constructs a client for the api.PrivateKVSService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPrivateKVSServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PrivateKVSServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &privateKVSServiceClient{
		getETagV1: connect.NewClient[api.PrivateKVSServiceGetETagV1Request, api.PrivateKVSServiceGetETagV1Response](
			httpClient,
			baseURL+PrivateKVSServiceGetETagV1Procedure,
			connect.WithSchema(privateKVSServiceGetETagV1MethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getV1: connect.NewClient[api.PrivateKVSServiceGetV1Request, api.PrivateKVSServiceGetV1Response](
			httpClient,
			baseURL+PrivateKVSServiceGetV1Procedure,
			connect.WithSchema(privateKVSServiceGetV1MethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		setV1: connect.NewClient[api.PrivateKVSServiceSetV1Request, api.PrivateKVSServiceSetV1Response](
			httpClient,
			baseURL+PrivateKVSServiceSetV1Procedure,
			connect.WithSchema(privateKVSServiceSetV1MethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// privateKVSServiceClient implements PrivateKVSServiceClient.
type privateKVSServiceClient struct {
	getETagV1 *connect.Client[api.PrivateKVSServiceGetETagV1Request, api.PrivateKVSServiceGetETagV1Response]
	getV1     *connect.Client[api.PrivateKVSServiceGetV1Request, api.PrivateKVSServiceGetV1Response]
	setV1     *connect.Client[api.PrivateKVSServiceSetV1Request, api.PrivateKVSServiceSetV1Response]
}

// GetETagV1 calls api.PrivateKVSService.GetETagV1.
func (c *privateKVSServiceClient) GetETagV1(ctx context.Context, req *connect.Request[api.PrivateKVSServiceGetETagV1Request]) (*connect.Response[api.PrivateKVSServiceGetETagV1Response], error) {
	return c.getETagV1.CallUnary(ctx, req)
}

// GetV1 calls api.PrivateKVSService.GetV1.
func (c *privateKVSServiceClient) GetV1(ctx context.Context, req *connect.Request[api.PrivateKVSServiceGetV1Request]) (*connect.Response[api.PrivateKVSServiceGetV1Response], error) {
	return c.getV1.CallUnary(ctx, req)
}

// SetV1 calls api.PrivateKVSService.SetV1.
func (c *privateKVSServiceClient) SetV1(ctx context.Context, req *connect.Request[api.PrivateKVSServiceSetV1Request]) (*connect.Response[api.PrivateKVSServiceSetV1Response], error) {
	return c.setV1.CallUnary(ctx, req)
}

// PrivateKVSServiceHandler is an implementation of the api.PrivateKVSService service.
type PrivateKVSServiceHandler interface {
	GetETagV1(context.Context, *connect.Request[api.PrivateKVSServiceGetETagV1Request]) (*connect.Response[api.PrivateKVSServiceGetETagV1Response], error)
	// KVS のエントリを検索します。
	// ただし、検索条件が空の場合は空リストを返します。
	GetV1(context.Context, *connect.Request[api.PrivateKVSServiceGetV1Request]) (*connect.Response[api.PrivateKVSServiceGetV1Response], error)
	// KVS にエントリを登録します。
	// エントリの作成、更新、削除を行うことが可能で、value が空のエントリは削除されます。
	SetV1(context.Context, *connect.Request[api.PrivateKVSServiceSetV1Request]) (*connect.Response[api.PrivateKVSServiceSetV1Response], error)
}

// NewPrivateKVSServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPrivateKVSServiceHandler(svc PrivateKVSServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	privateKVSServiceGetETagV1Handler := connect.NewUnaryHandler(
		PrivateKVSServiceGetETagV1Procedure,
		svc.GetETagV1,
		connect.WithSchema(privateKVSServiceGetETagV1MethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	privateKVSServiceGetV1Handler := connect.NewUnaryHandler(
		PrivateKVSServiceGetV1Procedure,
		svc.GetV1,
		connect.WithSchema(privateKVSServiceGetV1MethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	privateKVSServiceSetV1Handler := connect.NewUnaryHandler(
		PrivateKVSServiceSetV1Procedure,
		svc.SetV1,
		connect.WithSchema(privateKVSServiceSetV1MethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.PrivateKVSService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PrivateKVSServiceGetETagV1Procedure:
			privateKVSServiceGetETagV1Handler.ServeHTTP(w, r)
		case PrivateKVSServiceGetV1Procedure:
			privateKVSServiceGetV1Handler.ServeHTTP(w, r)
		case PrivateKVSServiceSetV1Procedure:
			privateKVSServiceSetV1Handler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPrivateKVSServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPrivateKVSServiceHandler struct{}

func (UnimplementedPrivateKVSServiceHandler) GetETagV1(context.Context, *connect.Request[api.PrivateKVSServiceGetETagV1Request]) (*connect.Response[api.PrivateKVSServiceGetETagV1Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.PrivateKVSService.GetETagV1 is not implemented"))
}

func (UnimplementedPrivateKVSServiceHandler) GetV1(context.Context, *connect.Request[api.PrivateKVSServiceGetV1Request]) (*connect.Response[api.PrivateKVSServiceGetV1Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.PrivateKVSService.GetV1 is not implemented"))
}

func (UnimplementedPrivateKVSServiceHandler) SetV1(context.Context, *connect.Request[api.PrivateKVSServiceSetV1Request]) (*connect.Response[api.PrivateKVSServiceSetV1Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.PrivateKVSService.SetV1 is not implemented"))
}
