services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 100
      start_period: 10s

  db-migrate:
    build:
      context: .
      dockerfile: ./docker/db-migrate/Dockerfile
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    depends_on:
      postgres:
        condition: service_healthy

  cloud-pubsub:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    platform: linux/amd64
    command: >
      bash -c 'gcloud beta emulators pubsub start --host-port=$${PUBSUB_EMULATOR_HOST}'
    environment:
      PUBSUB_EMULATOR_HOST: 0.0.0.0:8085
    ports:
      - 8085:8085

volumes:
  postgres:
