// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: resource/kvs.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVSCriterion_MatchingType int32

const (
	KVSCriterion_MATCHING_TYPE_UNSPECIFIED KVSCriterion_MatchingType = 0
	// 完全一致
	KVSCriterion_MATCHING_TYPE_EXACT_MATCH KVSCriterion_MatchingType = 1
	// 前方一致
	KVSCriterion_MATCHING_TYPE_PREFIX_MATCH KVSCriterion_MatchingType = 2
)

// Enum value maps for KVSCriterion_MatchingType.
var (
	KVSCriterion_MatchingType_name = map[int32]string{
		0: "MATCHING_TYPE_UNSPECIFIED",
		1: "MATCHING_TYPE_EXACT_MATCH",
		2: "MATCHING_TYPE_PREFIX_MATCH",
	}
	KVSCriterion_MatchingType_value = map[string]int32{
		"MATCHING_TYPE_UNSPECIFIED":  0,
		"MATCHING_TYPE_EXACT_MATCH":  1,
		"MATCHING_TYPE_PREFIX_MATCH": 2,
	}
)

func (x KVSCriterion_MatchingType) Enum() *KVSCriterion_MatchingType {
	p := new(KVSCriterion_MatchingType)
	*p = x
	return p
}

func (x KVSCriterion_MatchingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KVSCriterion_MatchingType) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_kvs_proto_enumTypes[0].Descriptor()
}

func (KVSCriterion_MatchingType) Type() protoreflect.EnumType {
	return &file_resource_kvs_proto_enumTypes[0]
}

func (x KVSCriterion_MatchingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KVSCriterion_MatchingType.Descriptor instead.
func (KVSCriterion_MatchingType) EnumDescriptor() ([]byte, []int) {
	return file_resource_kvs_proto_rawDescGZIP(), []int{1, 0}
}

type KVSEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 前方一致でエントリ検索する機能を提供しているので、関連する key には同一のプレフィックスを付与することを推奨します。
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// 最大 100 KiB まで格納できる
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KVSEntry) Reset() {
	*x = KVSEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_kvs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVSEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSEntry) ProtoMessage() {}

func (x *KVSEntry) ProtoReflect() protoreflect.Message {
	mi := &file_resource_kvs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSEntry.ProtoReflect.Descriptor instead.
func (*KVSEntry) Descriptor() ([]byte, []int) {
	return file_resource_kvs_proto_rawDescGZIP(), []int{0}
}

func (x *KVSEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVSEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// KVS エントリの検索条件
type KVSCriterion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string                    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MatchingType KVSCriterion_MatchingType `protobuf:"varint,2,opt,name=matching_type,json=matchingType,proto3,enum=resource.KVSCriterion_MatchingType" json:"matching_type,omitempty"`
}

func (x *KVSCriterion) Reset() {
	*x = KVSCriterion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_kvs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVSCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSCriterion) ProtoMessage() {}

func (x *KVSCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_resource_kvs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSCriterion.ProtoReflect.Descriptor instead.
func (*KVSCriterion) Descriptor() ([]byte, []int) {
	return file_resource_kvs_proto_rawDescGZIP(), []int{1}
}

func (x *KVSCriterion) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVSCriterion) GetMatchingType() KVSCriterion_MatchingType {
	if x != nil {
		return x.MatchingType
	}
	return KVSCriterion_MATCHING_TYPE_UNSPECIFIED
}

var File_resource_kvs_proto protoreflect.FileDescriptor

var file_resource_kvs_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x6b, 0x76, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x32,
	0x0a, 0x08, 0x4b, 0x56, 0x53, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xd8, 0x01, 0x0a, 0x0c, 0x4b, 0x56, 0x53, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72,
	0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x48, 0x0a, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x4b, 0x56, 0x53, 0x43, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x6c, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1d, 0x0a, 0x19, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d,
	0x0a, 0x19, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x45, 0x58, 0x41, 0x43, 0x54, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x01, 0x12, 0x1e, 0x0a,
	0x1a, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x49, 0x4e, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50,
	0x52, 0x45, 0x46, 0x49, 0x58, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x02, 0x42, 0x83, 0x01,
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x08,
	0x4b, 0x76, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x76, 0x65, 0x72, 0x61, 0x6b, 0x2f, 0x68, 0x62,
	0x61, 0x61, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0xa2, 0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0xca, 0x02, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0xe2, 0x02, 0x14, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_kvs_proto_rawDescOnce sync.Once
	file_resource_kvs_proto_rawDescData = file_resource_kvs_proto_rawDesc
)

func file_resource_kvs_proto_rawDescGZIP() []byte {
	file_resource_kvs_proto_rawDescOnce.Do(func() {
		file_resource_kvs_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_kvs_proto_rawDescData)
	})
	return file_resource_kvs_proto_rawDescData
}

var file_resource_kvs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_kvs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_kvs_proto_goTypes = []any{
	(KVSCriterion_MatchingType)(0), // 0: resource.KVSCriterion.MatchingType
	(*KVSEntry)(nil),               // 1: resource.KVSEntry
	(*KVSCriterion)(nil),           // 2: resource.KVSCriterion
}
var file_resource_kvs_proto_depIdxs = []int32{
	0, // 0: resource.KVSCriterion.matching_type:type_name -> resource.KVSCriterion.MatchingType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_resource_kvs_proto_init() }
func file_resource_kvs_proto_init() {
	if File_resource_kvs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resource_kvs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*KVSEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_kvs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*KVSCriterion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_kvs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_kvs_proto_goTypes,
		DependencyIndexes: file_resource_kvs_proto_depIdxs,
		EnumInfos:         file_resource_kvs_proto_enumTypes,
		MessageInfos:      file_resource_kvs_proto_msgTypes,
	}.Build()
	File_resource_kvs_proto = out.File
	file_resource_kvs_proto_rawDesc = nil
	file_resource_kvs_proto_goTypes = nil
	file_resource_kvs_proto_depIdxs = nil
}
