// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: api/lobby.proto

package api

import (
	resource "github.com/averak/hbaas/protobuf/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LobbyServiceSearchRoomsV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Types []resource.RoomType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=resource.RoomType" json:"types,omitempty"`
}

func (x *LobbyServiceSearchRoomsV1Request) Reset() {
	*x = LobbyServiceSearchRoomsV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lobby_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyServiceSearchRoomsV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyServiceSearchRoomsV1Request) ProtoMessage() {}

func (x *LobbyServiceSearchRoomsV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_lobby_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyServiceSearchRoomsV1Request.ProtoReflect.Descriptor instead.
func (*LobbyServiceSearchRoomsV1Request) Descriptor() ([]byte, []int) {
	return file_api_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *LobbyServiceSearchRoomsV1Request) GetTypes() []resource.RoomType {
	if x != nil {
		return x.Types
	}
	return nil
}

type LobbyServiceSearchRoomsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*resource.Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *LobbyServiceSearchRoomsV1Response) Reset() {
	*x = LobbyServiceSearchRoomsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lobby_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyServiceSearchRoomsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyServiceSearchRoomsV1Response) ProtoMessage() {}

func (x *LobbyServiceSearchRoomsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_lobby_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyServiceSearchRoomsV1Response.ProtoReflect.Descriptor instead.
func (*LobbyServiceSearchRoomsV1Response) Descriptor() ([]byte, []int) {
	return file_api_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *LobbyServiceSearchRoomsV1Response) GetRooms() []*resource.Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type LobbyServiceCreateRoomV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        resource.RoomType `protobuf:"varint,1,opt,name=type,proto3,enum=resource.RoomType" json:"type,omitempty"`
	MaxCapacity int64             `protobuf:"varint,2,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	Secret      string            `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Details     []byte            `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *LobbyServiceCreateRoomV1Request) Reset() {
	*x = LobbyServiceCreateRoomV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lobby_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyServiceCreateRoomV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyServiceCreateRoomV1Request) ProtoMessage() {}

func (x *LobbyServiceCreateRoomV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_lobby_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyServiceCreateRoomV1Request.ProtoReflect.Descriptor instead.
func (*LobbyServiceCreateRoomV1Request) Descriptor() ([]byte, []int) {
	return file_api_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *LobbyServiceCreateRoomV1Request) GetType() resource.RoomType {
	if x != nil {
		return x.Type
	}
	return resource.RoomType(0)
}

func (x *LobbyServiceCreateRoomV1Request) GetMaxCapacity() int64 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *LobbyServiceCreateRoomV1Request) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *LobbyServiceCreateRoomV1Request) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

type LobbyServiceCreateRoomV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *resource.Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *LobbyServiceCreateRoomV1Response) Reset() {
	*x = LobbyServiceCreateRoomV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lobby_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyServiceCreateRoomV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyServiceCreateRoomV1Response) ProtoMessage() {}

func (x *LobbyServiceCreateRoomV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_lobby_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyServiceCreateRoomV1Response.ProtoReflect.Descriptor instead.
func (*LobbyServiceCreateRoomV1Response) Descriptor() ([]byte, []int) {
	return file_api_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *LobbyServiceCreateRoomV1Response) GetRoom() *resource.Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type LobbyServiceDeleteRoomV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *LobbyServiceDeleteRoomV1Request) Reset() {
	*x = LobbyServiceDeleteRoomV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lobby_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyServiceDeleteRoomV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyServiceDeleteRoomV1Request) ProtoMessage() {}

func (x *LobbyServiceDeleteRoomV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_lobby_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyServiceDeleteRoomV1Request.ProtoReflect.Descriptor instead.
func (*LobbyServiceDeleteRoomV1Request) Descriptor() ([]byte, []int) {
	return file_api_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *LobbyServiceDeleteRoomV1Request) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LobbyServiceDeleteRoomV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LobbyServiceDeleteRoomV1Response) Reset() {
	*x = LobbyServiceDeleteRoomV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lobby_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyServiceDeleteRoomV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyServiceDeleteRoomV1Response) ProtoMessage() {}

func (x *LobbyServiceDeleteRoomV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_lobby_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyServiceDeleteRoomV1Response.ProtoReflect.Descriptor instead.
func (*LobbyServiceDeleteRoomV1Response) Descriptor() ([]byte, []int) {
	return file_api_lobby_proto_rawDescGZIP(), []int{5}
}

type LobbyServiceJoinRoomV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *LobbyServiceJoinRoomV1Request) Reset() {
	*x = LobbyServiceJoinRoomV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lobby_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyServiceJoinRoomV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyServiceJoinRoomV1Request) ProtoMessage() {}

func (x *LobbyServiceJoinRoomV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_lobby_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyServiceJoinRoomV1Request.ProtoReflect.Descriptor instead.
func (*LobbyServiceJoinRoomV1Request) Descriptor() ([]byte, []int) {
	return file_api_lobby_proto_rawDescGZIP(), []int{6}
}

func (x *LobbyServiceJoinRoomV1Request) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LobbyServiceJoinRoomV1Request) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type LobbyServiceJoinRoomV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// https://skyway.ntt.com/ja/docs/user-guide/authentication/skyway-auth-token/
	SkywayAuthToken string `protobuf:"bytes,1,opt,name=skyway_auth_token,json=skywayAuthToken,proto3" json:"skyway_auth_token,omitempty"`
	PeerId          string `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *LobbyServiceJoinRoomV1Response) Reset() {
	*x = LobbyServiceJoinRoomV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_lobby_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LobbyServiceJoinRoomV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyServiceJoinRoomV1Response) ProtoMessage() {}

func (x *LobbyServiceJoinRoomV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_lobby_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyServiceJoinRoomV1Response.ProtoReflect.Descriptor instead.
func (*LobbyServiceJoinRoomV1Response) Descriptor() ([]byte, []int) {
	return file_api_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *LobbyServiceJoinRoomV1Response) GetSkywayAuthToken() string {
	if x != nil {
		return x.SkywayAuthToken
	}
	return ""
}

func (x *LobbyServiceJoinRoomV1Response) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

var File_api_lobby_proto protoreflect.FileDescriptor

var file_api_lobby_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x14, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2f, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x20,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x49, 0x0a, 0x21, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x24, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x1f, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x43, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x46, 0x0a, 0x20, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x72, 0x6f,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x22, 0x3a,
	0x0a, 0x1f, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x20, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x50,
	0x0a, 0x1d, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x22, 0x65, 0x0a, 0x1e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x6b, 0x79, 0x77, 0x61, 0x79, 0x5f, 0x61, 0x75, 0x74,
	0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73,
	0x6b, 0x79, 0x77, 0x61, 0x79, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x32, 0xff, 0x02, 0x0a, 0x0c, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x56, 0x31, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x73, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c,
	0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x62, 0x62,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x55, 0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31,
	0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x62, 0x62, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x67, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x70, 0x69, 0x42, 0x0a, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x76, 0x65, 0x72, 0x61, 0x6b, 0x2f, 0x68, 0x62, 0x61, 0x61, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x70, 0x69, 0xa2, 0x02, 0x03, 0x41, 0x58, 0x58, 0xaa, 0x02,
	0x03, 0x41, 0x70, 0x69, 0xca, 0x02, 0x03, 0x41, 0x70, 0x69, 0xe2, 0x02, 0x0f, 0x41, 0x70, 0x69,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x03, 0x41,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_lobby_proto_rawDescOnce sync.Once
	file_api_lobby_proto_rawDescData = file_api_lobby_proto_rawDesc
)

func file_api_lobby_proto_rawDescGZIP() []byte {
	file_api_lobby_proto_rawDescOnce.Do(func() {
		file_api_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_lobby_proto_rawDescData)
	})
	return file_api_lobby_proto_rawDescData
}

var file_api_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_lobby_proto_goTypes = []any{
	(*LobbyServiceSearchRoomsV1Request)(nil),  // 0: api.LobbyServiceSearchRoomsV1Request
	(*LobbyServiceSearchRoomsV1Response)(nil), // 1: api.LobbyServiceSearchRoomsV1Response
	(*LobbyServiceCreateRoomV1Request)(nil),   // 2: api.LobbyServiceCreateRoomV1Request
	(*LobbyServiceCreateRoomV1Response)(nil),  // 3: api.LobbyServiceCreateRoomV1Response
	(*LobbyServiceDeleteRoomV1Request)(nil),   // 4: api.LobbyServiceDeleteRoomV1Request
	(*LobbyServiceDeleteRoomV1Response)(nil),  // 5: api.LobbyServiceDeleteRoomV1Response
	(*LobbyServiceJoinRoomV1Request)(nil),     // 6: api.LobbyServiceJoinRoomV1Request
	(*LobbyServiceJoinRoomV1Response)(nil),    // 7: api.LobbyServiceJoinRoomV1Response
	(resource.RoomType)(0),                    // 8: resource.RoomType
	(*resource.Room)(nil),                     // 9: resource.Room
}
var file_api_lobby_proto_depIdxs = []int32{
	8, // 0: api.LobbyServiceSearchRoomsV1Request.types:type_name -> resource.RoomType
	9, // 1: api.LobbyServiceSearchRoomsV1Response.rooms:type_name -> resource.Room
	8, // 2: api.LobbyServiceCreateRoomV1Request.type:type_name -> resource.RoomType
	9, // 3: api.LobbyServiceCreateRoomV1Response.room:type_name -> resource.Room
	0, // 4: api.LobbyService.SearchRoomsV1:input_type -> api.LobbyServiceSearchRoomsV1Request
	2, // 5: api.LobbyService.CreateRoomV1:input_type -> api.LobbyServiceCreateRoomV1Request
	4, // 6: api.LobbyService.DeleteRoomV1:input_type -> api.LobbyServiceDeleteRoomV1Request
	6, // 7: api.LobbyService.JoinRoomV1:input_type -> api.LobbyServiceJoinRoomV1Request
	1, // 8: api.LobbyService.SearchRoomsV1:output_type -> api.LobbyServiceSearchRoomsV1Response
	3, // 9: api.LobbyService.CreateRoomV1:output_type -> api.LobbyServiceCreateRoomV1Response
	5, // 10: api.LobbyService.DeleteRoomV1:output_type -> api.LobbyServiceDeleteRoomV1Response
	7, // 11: api.LobbyService.JoinRoomV1:output_type -> api.LobbyServiceJoinRoomV1Response
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_lobby_proto_init() }
func file_api_lobby_proto_init() {
	if File_api_lobby_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_lobby_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyServiceSearchRoomsV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lobby_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyServiceSearchRoomsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lobby_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyServiceCreateRoomV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lobby_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyServiceCreateRoomV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lobby_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyServiceDeleteRoomV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lobby_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyServiceDeleteRoomV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lobby_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyServiceJoinRoomV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_lobby_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*LobbyServiceJoinRoomV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_lobby_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lobby_proto_goTypes,
		DependencyIndexes: file_api_lobby_proto_depIdxs,
		MessageInfos:      file_api_lobby_proto_msgTypes,
	}.Build()
	File_api_lobby_proto = out.File
	file_api_lobby_proto_rawDesc = nil
	file_api_lobby_proto_goTypes = nil
	file_api_lobby_proto_depIdxs = nil
}
