// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"github.com/averak/hbaas/app/adapter/handler"
	"github.com/averak/hbaas/app/adapter/handler/debug/echo"
	"github.com/averak/hbaas/app/adapter/repoimpl"
	"github.com/averak/hbaas/app/adapter/repoimpl/echo_repoimpl"
	"github.com/averak/hbaas/app/infrastructure/db"
	"github.com/averak/hbaas/app/usecase"
	"github.com/averak/hbaas/app/usecase/echo_usecase"
	"github.com/google/wire"
	"net/http"
)

// Injectors from wire.go:

func InitializeAPIServerMux(ctx context.Context) (*http.ServeMux, error) {
	connection, err := db.NewConnection()
	if err != nil {
		return nil, err
	}
	echoRepository := echo_repoimpl.New()
	usecase := echo_usecase.New(connection, echoRepository)
	echoServiceHandler := echo.New(usecase)
	serveMux := handler.New(echoServiceHandler)
	return serveMux, nil
}

// wire.go:

var SuperSet = wire.NewSet(repoimpl.SuperSet, usecase.SuperSet, db.NewConnection)
