// Code generated by github.com/averak/hbaas/cmd/protoc-gen-hbaas-server. DO NOT EDIT.
// source: api/debug/echo.proto

package debug

import (
	connect "connectrpc.com/connect"
	context "context"
	connect1 "github.com/averak/hbaas/app/infrastructure/connect"
	advice "github.com/averak/hbaas/app/infrastructure/connect/advice"
	custom_option "github.com/averak/hbaas/protobuf/custom_option"
	proto "google.golang.org/protobuf/proto"
)

type hbaas_EchoServiceHandler interface {
	EchoV1(ctx context.Context, req *advice.Request[*EchoServiceEchoV1Request]) (*EchoServiceEchoV1Response, error)
}

func NewEchoServiceHandler(handler hbaas_EchoServiceHandler, adv advice.Advice) hbaas_EchoServiceHandlerImpl {
	service := File_api_debug_echo_proto.Services().ByName("EchoService")
	causes := [1]map[error]*advice.MethodErrDefinition{{}}
	methodOpts := [1]*advice.MethodOption{}
	for i, m := 0, service.Methods(); i < 1; i++ {
		methodOpts[i] = proto.GetExtension(m.Get(i).Options(), custom_option.E_MethodOption).(*advice.MethodOption)
	}
	methodInfo := [1]*advice.MethodInfo{
		advice.NewMethodInfo(methodOpts[0], causes[0]),
	}
	return hbaas_EchoServiceHandlerImpl{handler: handler, advice: adv, methodInfo: methodInfo}
}

type hbaas_EchoServiceHandlerImpl struct {
	handler    hbaas_EchoServiceHandler
	advice     advice.Advice
	methodInfo [1]*advice.MethodInfo
}

func (h hbaas_EchoServiceHandlerImpl) EchoV1(ctx context.Context, req *connect.Request[EchoServiceEchoV1Request]) (*connect.Response[EchoServiceEchoV1Response], error) {
	res, err := connect1.Execute(ctx, req.Msg, req.Header(), h.methodInfo[0], h.handler.EchoV1, h.advice)
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(res), nil
}
