// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

var TableNames = struct {
	Echos               string
	GlobalKVSEntries    string
	UserAuthentications string
	Users               string
}{
	Echos:               "echos",
	GlobalKVSEntries:    "global_kvs_entries",
	UserAuthentications: "user_authentications",
	Users:               "users",
}
