// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PrivateKVSEtag is an object representing the database table.
type PrivateKVSEtag struct {
	UserID    string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Etag      string    `boil:"etag" json:"etag" toml:"etag" yaml:"etag"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *privateKVSEtagR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L privateKVSEtagL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PrivateKVSEtagColumns = struct {
	UserID    string
	Etag      string
	CreatedAt string
	UpdatedAt string
}{
	UserID:    "user_id",
	Etag:      "etag",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var PrivateKVSEtagTableColumns = struct {
	UserID    string
	Etag      string
	CreatedAt string
	UpdatedAt string
}{
	UserID:    "private_kvs_etags.user_id",
	Etag:      "private_kvs_etags.etag",
	CreatedAt: "private_kvs_etags.created_at",
	UpdatedAt: "private_kvs_etags.updated_at",
}

// Generated where

var PrivateKVSEtagWhere = struct {
	UserID    whereHelperstring
	Etag      whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	UserID:    whereHelperstring{field: "\"private_kvs_etags\".\"user_id\""},
	Etag:      whereHelperstring{field: "\"private_kvs_etags\".\"etag\""},
	CreatedAt: whereHelpertime_Time{field: "\"private_kvs_etags\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"private_kvs_etags\".\"updated_at\""},
}

// PrivateKVSEtagRels is where relationship names are stored.
var PrivateKVSEtagRels = struct {
	User string
}{
	User: "User",
}

// privateKVSEtagR is where relationships are stored.
type privateKVSEtagR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*privateKVSEtagR) NewStruct() *privateKVSEtagR {
	return &privateKVSEtagR{}
}

func (r *privateKVSEtagR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// privateKVSEtagL is where Load methods for each relationship are stored.
type privateKVSEtagL struct{}

var (
	privateKVSEtagAllColumns            = []string{"user_id", "etag", "created_at", "updated_at"}
	privateKVSEtagColumnsWithoutDefault = []string{"user_id", "etag", "created_at", "updated_at"}
	privateKVSEtagColumnsWithDefault    = []string{}
	privateKVSEtagPrimaryKeyColumns     = []string{"user_id"}
	privateKVSEtagGeneratedColumns      = []string{}
)

type (
	// PrivateKVSEtagSlice is an alias for a slice of pointers to PrivateKVSEtag.
	// This should almost always be used instead of []PrivateKVSEtag.
	PrivateKVSEtagSlice []*PrivateKVSEtag
	// PrivateKVSEtagHook is the signature for custom PrivateKVSEtag hook methods
	PrivateKVSEtagHook func(context.Context, boil.ContextExecutor, *PrivateKVSEtag) error

	privateKVSEtagQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	privateKVSEtagType                 = reflect.TypeOf(&PrivateKVSEtag{})
	privateKVSEtagMapping              = queries.MakeStructMapping(privateKVSEtagType)
	privateKVSEtagPrimaryKeyMapping, _ = queries.BindMapping(privateKVSEtagType, privateKVSEtagMapping, privateKVSEtagPrimaryKeyColumns)
	privateKVSEtagInsertCacheMut       sync.RWMutex
	privateKVSEtagInsertCache          = make(map[string]insertCache)
	privateKVSEtagUpdateCacheMut       sync.RWMutex
	privateKVSEtagUpdateCache          = make(map[string]updateCache)
	privateKVSEtagUpsertCacheMut       sync.RWMutex
	privateKVSEtagUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var privateKVSEtagAfterSelectMu sync.Mutex
var privateKVSEtagAfterSelectHooks []PrivateKVSEtagHook

var privateKVSEtagBeforeInsertMu sync.Mutex
var privateKVSEtagBeforeInsertHooks []PrivateKVSEtagHook
var privateKVSEtagAfterInsertMu sync.Mutex
var privateKVSEtagAfterInsertHooks []PrivateKVSEtagHook

var privateKVSEtagBeforeUpdateMu sync.Mutex
var privateKVSEtagBeforeUpdateHooks []PrivateKVSEtagHook
var privateKVSEtagAfterUpdateMu sync.Mutex
var privateKVSEtagAfterUpdateHooks []PrivateKVSEtagHook

var privateKVSEtagBeforeDeleteMu sync.Mutex
var privateKVSEtagBeforeDeleteHooks []PrivateKVSEtagHook
var privateKVSEtagAfterDeleteMu sync.Mutex
var privateKVSEtagAfterDeleteHooks []PrivateKVSEtagHook

var privateKVSEtagBeforeUpsertMu sync.Mutex
var privateKVSEtagBeforeUpsertHooks []PrivateKVSEtagHook
var privateKVSEtagAfterUpsertMu sync.Mutex
var privateKVSEtagAfterUpsertHooks []PrivateKVSEtagHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PrivateKVSEtag) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PrivateKVSEtag) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PrivateKVSEtag) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PrivateKVSEtag) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PrivateKVSEtag) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PrivateKVSEtag) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PrivateKVSEtag) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PrivateKVSEtag) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PrivateKVSEtag) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEtagAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPrivateKVSEtagHook registers your hook function for all future operations.
func AddPrivateKVSEtagHook(hookPoint boil.HookPoint, privateKVSEtagHook PrivateKVSEtagHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		privateKVSEtagAfterSelectMu.Lock()
		privateKVSEtagAfterSelectHooks = append(privateKVSEtagAfterSelectHooks, privateKVSEtagHook)
		privateKVSEtagAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		privateKVSEtagBeforeInsertMu.Lock()
		privateKVSEtagBeforeInsertHooks = append(privateKVSEtagBeforeInsertHooks, privateKVSEtagHook)
		privateKVSEtagBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		privateKVSEtagAfterInsertMu.Lock()
		privateKVSEtagAfterInsertHooks = append(privateKVSEtagAfterInsertHooks, privateKVSEtagHook)
		privateKVSEtagAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		privateKVSEtagBeforeUpdateMu.Lock()
		privateKVSEtagBeforeUpdateHooks = append(privateKVSEtagBeforeUpdateHooks, privateKVSEtagHook)
		privateKVSEtagBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		privateKVSEtagAfterUpdateMu.Lock()
		privateKVSEtagAfterUpdateHooks = append(privateKVSEtagAfterUpdateHooks, privateKVSEtagHook)
		privateKVSEtagAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		privateKVSEtagBeforeDeleteMu.Lock()
		privateKVSEtagBeforeDeleteHooks = append(privateKVSEtagBeforeDeleteHooks, privateKVSEtagHook)
		privateKVSEtagBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		privateKVSEtagAfterDeleteMu.Lock()
		privateKVSEtagAfterDeleteHooks = append(privateKVSEtagAfterDeleteHooks, privateKVSEtagHook)
		privateKVSEtagAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		privateKVSEtagBeforeUpsertMu.Lock()
		privateKVSEtagBeforeUpsertHooks = append(privateKVSEtagBeforeUpsertHooks, privateKVSEtagHook)
		privateKVSEtagBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		privateKVSEtagAfterUpsertMu.Lock()
		privateKVSEtagAfterUpsertHooks = append(privateKVSEtagAfterUpsertHooks, privateKVSEtagHook)
		privateKVSEtagAfterUpsertMu.Unlock()
	}
}

// One returns a single privateKVSEtag record from the query.
func (q privateKVSEtagQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PrivateKVSEtag, error) {
	o := &PrivateKVSEtag{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dao: failed to execute a one query for private_kvs_etags")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PrivateKVSEtag records from the query.
func (q privateKVSEtagQuery) All(ctx context.Context, exec boil.ContextExecutor) (PrivateKVSEtagSlice, error) {
	var o []*PrivateKVSEtag

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dao: failed to assign all query results to PrivateKVSEtag slice")
	}

	if len(privateKVSEtagAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PrivateKVSEtag records in the query.
func (q privateKVSEtagQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to count private_kvs_etags rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q privateKVSEtagQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dao: failed to check if private_kvs_etags exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *PrivateKVSEtag) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (privateKVSEtagL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybePrivateKVSEtag interface{}, mods queries.Applicator) error {
	var slice []*PrivateKVSEtag
	var object *PrivateKVSEtag

	if singular {
		var ok bool
		object, ok = maybePrivateKVSEtag.(*PrivateKVSEtag)
		if !ok {
			object = new(PrivateKVSEtag)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePrivateKVSEtag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePrivateKVSEtag))
			}
		}
	} else {
		s, ok := maybePrivateKVSEtag.(*[]*PrivateKVSEtag)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePrivateKVSEtag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePrivateKVSEtag))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &privateKVSEtagR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &privateKVSEtagR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.PrivateKVSEtag = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.PrivateKVSEtag = local
				break
			}
		}
	}

	return nil
}

// SetUser of the privateKVSEtag to the related item.
// Sets o.R.User to related.
// Adds o to related.R.PrivateKVSEtag.
func (o *PrivateKVSEtag) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"private_kvs_etags\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, privateKVSEtagPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &privateKVSEtagR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			PrivateKVSEtag: o,
		}
	} else {
		related.R.PrivateKVSEtag = o
	}

	return nil
}

// PrivateKVSEtags retrieves all the records using an executor.
func PrivateKVSEtags(mods ...qm.QueryMod) privateKVSEtagQuery {
	mods = append(mods, qm.From("\"private_kvs_etags\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"private_kvs_etags\".*"})
	}

	return privateKVSEtagQuery{q}
}

// FindPrivateKVSEtag retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPrivateKVSEtag(ctx context.Context, exec boil.ContextExecutor, userID string, selectCols ...string) (*PrivateKVSEtag, error) {
	privateKVSEtagObj := &PrivateKVSEtag{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"private_kvs_etags\" where \"user_id\"=$1", sel,
	)

	q := queries.Raw(query, userID)

	err := q.Bind(ctx, exec, privateKVSEtagObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dao: unable to select from private_kvs_etags")
	}

	if err = privateKVSEtagObj.doAfterSelectHooks(ctx, exec); err != nil {
		return privateKVSEtagObj, err
	}

	return privateKVSEtagObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PrivateKVSEtag) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dao: no private_kvs_etags provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(privateKVSEtagColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	privateKVSEtagInsertCacheMut.RLock()
	cache, cached := privateKVSEtagInsertCache[key]
	privateKVSEtagInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			privateKVSEtagAllColumns,
			privateKVSEtagColumnsWithDefault,
			privateKVSEtagColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(privateKVSEtagType, privateKVSEtagMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(privateKVSEtagType, privateKVSEtagMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"private_kvs_etags\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"private_kvs_etags\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dao: unable to insert into private_kvs_etags")
	}

	if !cached {
		privateKVSEtagInsertCacheMut.Lock()
		privateKVSEtagInsertCache[key] = cache
		privateKVSEtagInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PrivateKVSEtag.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PrivateKVSEtag) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	privateKVSEtagUpdateCacheMut.RLock()
	cache, cached := privateKVSEtagUpdateCache[key]
	privateKVSEtagUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			privateKVSEtagAllColumns,
			privateKVSEtagPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dao: unable to update private_kvs_etags, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"private_kvs_etags\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, privateKVSEtagPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(privateKVSEtagType, privateKVSEtagMapping, append(wl, privateKVSEtagPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update private_kvs_etags row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by update for private_kvs_etags")
	}

	if !cached {
		privateKVSEtagUpdateCacheMut.Lock()
		privateKVSEtagUpdateCache[key] = cache
		privateKVSEtagUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q privateKVSEtagQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update all for private_kvs_etags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to retrieve rows affected for private_kvs_etags")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PrivateKVSEtagSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dao: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), privateKVSEtagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"private_kvs_etags\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, privateKVSEtagPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update all in privateKVSEtag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to retrieve rows affected all in update all privateKVSEtag")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PrivateKVSEtag) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dao: no private_kvs_etags provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(privateKVSEtagColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	privateKVSEtagUpsertCacheMut.RLock()
	cache, cached := privateKVSEtagUpsertCache[key]
	privateKVSEtagUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			privateKVSEtagAllColumns,
			privateKVSEtagColumnsWithDefault,
			privateKVSEtagColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			privateKVSEtagAllColumns,
			privateKVSEtagPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dao: unable to upsert private_kvs_etags, could not build update column list")
		}

		ret := strmangle.SetComplement(privateKVSEtagAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(privateKVSEtagPrimaryKeyColumns) == 0 {
				return errors.New("dao: unable to upsert private_kvs_etags, could not build conflict column list")
			}

			conflict = make([]string, len(privateKVSEtagPrimaryKeyColumns))
			copy(conflict, privateKVSEtagPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"private_kvs_etags\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(privateKVSEtagType, privateKVSEtagMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(privateKVSEtagType, privateKVSEtagMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dao: unable to upsert private_kvs_etags")
	}

	if !cached {
		privateKVSEtagUpsertCacheMut.Lock()
		privateKVSEtagUpsertCache[key] = cache
		privateKVSEtagUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PrivateKVSEtag record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PrivateKVSEtag) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dao: no PrivateKVSEtag provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), privateKVSEtagPrimaryKeyMapping)
	sql := "DELETE FROM \"private_kvs_etags\" WHERE \"user_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete from private_kvs_etags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by delete for private_kvs_etags")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q privateKVSEtagQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dao: no privateKVSEtagQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete all from private_kvs_etags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by deleteall for private_kvs_etags")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PrivateKVSEtagSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(privateKVSEtagBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), privateKVSEtagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"private_kvs_etags\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, privateKVSEtagPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete all from privateKVSEtag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by deleteall for private_kvs_etags")
	}

	if len(privateKVSEtagAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PrivateKVSEtag) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPrivateKVSEtag(ctx, exec, o.UserID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PrivateKVSEtagSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PrivateKVSEtagSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), privateKVSEtagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"private_kvs_etags\".* FROM \"private_kvs_etags\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, privateKVSEtagPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dao: unable to reload all in PrivateKVSEtagSlice")
	}

	*o = slice

	return nil
}

// PrivateKVSEtagExists checks if the PrivateKVSEtag row exists.
func PrivateKVSEtagExists(ctx context.Context, exec boil.ContextExecutor, userID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"private_kvs_etags\" where \"user_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID)
	}
	row := exec.QueryRowContext(ctx, sql, userID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dao: unable to check if private_kvs_etags exists")
	}

	return exists, nil
}

// Exists checks if the PrivateKVSEtag row exists.
func (o *PrivateKVSEtag) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PrivateKVSEtagExists(ctx, exec, o.UserID)
}

// /////////////////////////////// BEGIN EXTENSIONS /////////////////////////////////
// Expose table columns
var (
	PrivateKVSEtagAllColumns            = privateKVSEtagAllColumns
	PrivateKVSEtagColumnsWithoutDefault = privateKVSEtagColumnsWithoutDefault
	PrivateKVSEtagColumnsWithDefault    = privateKVSEtagColumnsWithDefault
	PrivateKVSEtagPrimaryKeyColumns     = privateKVSEtagPrimaryKeyColumns
	PrivateKVSEtagGeneratedColumns      = privateKVSEtagGeneratedColumns
)

// InsertAll inserts all rows with the specified column values, using an executor.
func (o PrivateKVSEtagSlice) InsertAll(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var sql string
	vals := []interface{}{}
	for i, row := range o {
		if !boil.TimestampsAreSkipped(ctx) {
			currTime := time.Now().In(boil.GetLocation())
			if row.CreatedAt.IsZero() {
				row.CreatedAt = currTime
			}
			if row.UpdatedAt.IsZero() {
				row.UpdatedAt = currTime
			}
		}

		if err := row.doBeforeInsertHooks(ctx, exec); err != nil {
			return 0, err
		}

		wl, _ := columns.InsertColumnSet(
			privateKVSEtagAllColumns,
			privateKVSEtagColumnsWithDefault,
			privateKVSEtagColumnsWithoutDefault,
			queries.NonZeroDefaultSet(privateKVSEtagColumnsWithDefault, row),
		)
		if i == 0 {
			sql = "INSERT INTO \"private_kvs_etags\" " + "(\"" + strings.Join(wl, "\",\"") + "\")" + " VALUES "
		}
		sql += strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), len(vals)+1, len(wl))
		if i != len(o)-1 {
			sql += ","
		}
		valMapping, err := queries.BindMapping(privateKVSEtagType, privateKVSEtagMapping, wl)
		if err != nil {
			return 0, err
		}

		value := reflect.Indirect(reflect.ValueOf(row))
		vals = append(vals, queries.ValuesFromMapping(value, valMapping)...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, vals)
	}

	result, err := exec.ExecContext(ctx, sql, vals...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to insert all from privateKVSEtag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by insertall for private_kvs_etags")
	}

	if len(privateKVSEtagAfterInsertHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterInsertHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// UpsertAll inserts or updates all rows
// Currently it doesn't support "NoContext" and "NoRowsAffected"
func (o PrivateKVSEtagSlice) UpsertAll(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	nzDefaults := queries.NonZeroDefaultSet(privateKVSEtagColumnsWithDefault, o[0])

	insert, _ := insertColumns.InsertColumnSet(
		privateKVSEtagAllColumns,
		privateKVSEtagColumnsWithDefault,
		privateKVSEtagColumnsWithoutDefault,
		nzDefaults,
	)
	update := updateColumns.UpdateColumnSet(
		privateKVSEtagAllColumns,
		privateKVSEtagPrimaryKeyColumns,
	)

	if updateOnConflict && len(update) == 0 {
		return 0, errors.New("dao: unable to upsert private_kvs_etags, could not build update column list")
	}

	conflict := conflictColumns
	if len(conflict) == 0 {
		conflict = make([]string, len(privateKVSEtagPrimaryKeyColumns))
		copy(conflict, privateKVSEtagPrimaryKeyColumns)
	}

	buf := strmangle.GetBuffer()
	defer strmangle.PutBuffer(buf)

	columns := "DEFAULT VALUES"
	if len(insert) != 0 {
		columns = fmt.Sprintf("(%s) VALUES %s",
			strings.Join(insert, ", "),
			strmangle.Placeholders(dialect.UseIndexPlaceholders, len(insert)*len(o), 1, len(insert)),
		)
	}

	fmt.Fprintf(
		buf,
		"INSERT INTO %s %s ON CONFLICT ",
		"\"private_kvs_etags\"",
		columns,
	)

	if !updateOnConflict || len(update) == 0 {
		buf.WriteString("DO NOTHING")
	} else {
		buf.WriteByte('(')
		buf.WriteString(strings.Join(conflict, ", "))
		buf.WriteString(") DO UPDATE SET ")

		for i, v := range update {
			if i != 0 {
				buf.WriteByte(',')
			}
			quoted := strmangle.IdentQuote(dialect.LQ, dialect.RQ, v)
			buf.WriteString(quoted)
			buf.WriteString(" = EXCLUDED.")
			buf.WriteString(quoted)
		}
	}

	query := buf.String()
	valueMapping, err := queries.BindMapping(privateKVSEtagType, privateKVSEtagMapping, insert)
	if err != nil {
		return 0, err
	}

	var vals []interface{}
	for _, row := range o {
		if !boil.TimestampsAreSkipped(ctx) {
			currTime := time.Now().In(boil.GetLocation())
			if row.CreatedAt.IsZero() {
				row.CreatedAt = currTime
			}

			row.UpdatedAt = currTime
		}

		if err := row.doBeforeUpsertHooks(ctx, exec); err != nil {
			return 0, err
		}

		value := reflect.Indirect(reflect.ValueOf(row))
		vals = append(vals, queries.ValuesFromMapping(value, valueMapping)...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, vals)
	}

	result, err := exec.ExecContext(ctx, query, vals...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to upsert for private_kvs_etags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by upsert for private_kvs_etags")
	}

	if len(privateKVSEtagAfterUpsertHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterUpsertHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

///////////////////////////////// END EXTENSIONS /////////////////////////////////
