// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PrivateKVSEntry is an object representing the database table.
type PrivateKVSEntry struct {
	UserID    string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Key       string    `boil:"key" json:"key" toml:"key" yaml:"key"`
	Value     []byte    `boil:"value" json:"value" toml:"value" yaml:"value"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *privateKVSEntryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L privateKVSEntryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PrivateKVSEntryColumns = struct {
	UserID    string
	Key       string
	Value     string
	CreatedAt string
	UpdatedAt string
}{
	UserID:    "user_id",
	Key:       "key",
	Value:     "value",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var PrivateKVSEntryTableColumns = struct {
	UserID    string
	Key       string
	Value     string
	CreatedAt string
	UpdatedAt string
}{
	UserID:    "private_kvs_entries.user_id",
	Key:       "private_kvs_entries.key",
	Value:     "private_kvs_entries.value",
	CreatedAt: "private_kvs_entries.created_at",
	UpdatedAt: "private_kvs_entries.updated_at",
}

// Generated where

var PrivateKVSEntryWhere = struct {
	UserID    whereHelperstring
	Key       whereHelperstring
	Value     whereHelper__byte
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	UserID:    whereHelperstring{field: "\"private_kvs_entries\".\"user_id\""},
	Key:       whereHelperstring{field: "\"private_kvs_entries\".\"key\""},
	Value:     whereHelper__byte{field: "\"private_kvs_entries\".\"value\""},
	CreatedAt: whereHelpertime_Time{field: "\"private_kvs_entries\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"private_kvs_entries\".\"updated_at\""},
}

// PrivateKVSEntryRels is where relationship names are stored.
var PrivateKVSEntryRels = struct {
	User string
}{
	User: "User",
}

// privateKVSEntryR is where relationships are stored.
type privateKVSEntryR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*privateKVSEntryR) NewStruct() *privateKVSEntryR {
	return &privateKVSEntryR{}
}

func (r *privateKVSEntryR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// privateKVSEntryL is where Load methods for each relationship are stored.
type privateKVSEntryL struct{}

var (
	privateKVSEntryAllColumns            = []string{"user_id", "key", "value", "created_at", "updated_at"}
	privateKVSEntryColumnsWithoutDefault = []string{"user_id", "key", "value", "created_at", "updated_at"}
	privateKVSEntryColumnsWithDefault    = []string{}
	privateKVSEntryPrimaryKeyColumns     = []string{"user_id", "key"}
	privateKVSEntryGeneratedColumns      = []string{}
)

type (
	// PrivateKVSEntrySlice is an alias for a slice of pointers to PrivateKVSEntry.
	// This should almost always be used instead of []PrivateKVSEntry.
	PrivateKVSEntrySlice []*PrivateKVSEntry
	// PrivateKVSEntryHook is the signature for custom PrivateKVSEntry hook methods
	PrivateKVSEntryHook func(context.Context, boil.ContextExecutor, *PrivateKVSEntry) error

	privateKVSEntryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	privateKVSEntryType                 = reflect.TypeOf(&PrivateKVSEntry{})
	privateKVSEntryMapping              = queries.MakeStructMapping(privateKVSEntryType)
	privateKVSEntryPrimaryKeyMapping, _ = queries.BindMapping(privateKVSEntryType, privateKVSEntryMapping, privateKVSEntryPrimaryKeyColumns)
	privateKVSEntryInsertCacheMut       sync.RWMutex
	privateKVSEntryInsertCache          = make(map[string]insertCache)
	privateKVSEntryUpdateCacheMut       sync.RWMutex
	privateKVSEntryUpdateCache          = make(map[string]updateCache)
	privateKVSEntryUpsertCacheMut       sync.RWMutex
	privateKVSEntryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var privateKVSEntryAfterSelectMu sync.Mutex
var privateKVSEntryAfterSelectHooks []PrivateKVSEntryHook

var privateKVSEntryBeforeInsertMu sync.Mutex
var privateKVSEntryBeforeInsertHooks []PrivateKVSEntryHook
var privateKVSEntryAfterInsertMu sync.Mutex
var privateKVSEntryAfterInsertHooks []PrivateKVSEntryHook

var privateKVSEntryBeforeUpdateMu sync.Mutex
var privateKVSEntryBeforeUpdateHooks []PrivateKVSEntryHook
var privateKVSEntryAfterUpdateMu sync.Mutex
var privateKVSEntryAfterUpdateHooks []PrivateKVSEntryHook

var privateKVSEntryBeforeDeleteMu sync.Mutex
var privateKVSEntryBeforeDeleteHooks []PrivateKVSEntryHook
var privateKVSEntryAfterDeleteMu sync.Mutex
var privateKVSEntryAfterDeleteHooks []PrivateKVSEntryHook

var privateKVSEntryBeforeUpsertMu sync.Mutex
var privateKVSEntryBeforeUpsertHooks []PrivateKVSEntryHook
var privateKVSEntryAfterUpsertMu sync.Mutex
var privateKVSEntryAfterUpsertHooks []PrivateKVSEntryHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PrivateKVSEntry) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PrivateKVSEntry) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PrivateKVSEntry) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PrivateKVSEntry) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PrivateKVSEntry) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PrivateKVSEntry) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PrivateKVSEntry) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PrivateKVSEntry) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PrivateKVSEntry) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range privateKVSEntryAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPrivateKVSEntryHook registers your hook function for all future operations.
func AddPrivateKVSEntryHook(hookPoint boil.HookPoint, privateKVSEntryHook PrivateKVSEntryHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		privateKVSEntryAfterSelectMu.Lock()
		privateKVSEntryAfterSelectHooks = append(privateKVSEntryAfterSelectHooks, privateKVSEntryHook)
		privateKVSEntryAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		privateKVSEntryBeforeInsertMu.Lock()
		privateKVSEntryBeforeInsertHooks = append(privateKVSEntryBeforeInsertHooks, privateKVSEntryHook)
		privateKVSEntryBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		privateKVSEntryAfterInsertMu.Lock()
		privateKVSEntryAfterInsertHooks = append(privateKVSEntryAfterInsertHooks, privateKVSEntryHook)
		privateKVSEntryAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		privateKVSEntryBeforeUpdateMu.Lock()
		privateKVSEntryBeforeUpdateHooks = append(privateKVSEntryBeforeUpdateHooks, privateKVSEntryHook)
		privateKVSEntryBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		privateKVSEntryAfterUpdateMu.Lock()
		privateKVSEntryAfterUpdateHooks = append(privateKVSEntryAfterUpdateHooks, privateKVSEntryHook)
		privateKVSEntryAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		privateKVSEntryBeforeDeleteMu.Lock()
		privateKVSEntryBeforeDeleteHooks = append(privateKVSEntryBeforeDeleteHooks, privateKVSEntryHook)
		privateKVSEntryBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		privateKVSEntryAfterDeleteMu.Lock()
		privateKVSEntryAfterDeleteHooks = append(privateKVSEntryAfterDeleteHooks, privateKVSEntryHook)
		privateKVSEntryAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		privateKVSEntryBeforeUpsertMu.Lock()
		privateKVSEntryBeforeUpsertHooks = append(privateKVSEntryBeforeUpsertHooks, privateKVSEntryHook)
		privateKVSEntryBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		privateKVSEntryAfterUpsertMu.Lock()
		privateKVSEntryAfterUpsertHooks = append(privateKVSEntryAfterUpsertHooks, privateKVSEntryHook)
		privateKVSEntryAfterUpsertMu.Unlock()
	}
}

// One returns a single privateKVSEntry record from the query.
func (q privateKVSEntryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PrivateKVSEntry, error) {
	o := &PrivateKVSEntry{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dao: failed to execute a one query for private_kvs_entries")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PrivateKVSEntry records from the query.
func (q privateKVSEntryQuery) All(ctx context.Context, exec boil.ContextExecutor) (PrivateKVSEntrySlice, error) {
	var o []*PrivateKVSEntry

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dao: failed to assign all query results to PrivateKVSEntry slice")
	}

	if len(privateKVSEntryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PrivateKVSEntry records in the query.
func (q privateKVSEntryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to count private_kvs_entries rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q privateKVSEntryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dao: failed to check if private_kvs_entries exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *PrivateKVSEntry) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (privateKVSEntryL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybePrivateKVSEntry interface{}, mods queries.Applicator) error {
	var slice []*PrivateKVSEntry
	var object *PrivateKVSEntry

	if singular {
		var ok bool
		object, ok = maybePrivateKVSEntry.(*PrivateKVSEntry)
		if !ok {
			object = new(PrivateKVSEntry)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePrivateKVSEntry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePrivateKVSEntry))
			}
		}
	} else {
		s, ok := maybePrivateKVSEntry.(*[]*PrivateKVSEntry)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePrivateKVSEntry)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePrivateKVSEntry))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &privateKVSEntryR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &privateKVSEntryR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.PrivateKVSEntries = append(foreign.R.PrivateKVSEntries, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.PrivateKVSEntries = append(foreign.R.PrivateKVSEntries, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the privateKVSEntry to the related item.
// Sets o.R.User to related.
// Adds o to related.R.PrivateKVSEntries.
func (o *PrivateKVSEntry) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"private_kvs_entries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, privateKVSEntryPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.Key}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &privateKVSEntryR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			PrivateKVSEntries: PrivateKVSEntrySlice{o},
		}
	} else {
		related.R.PrivateKVSEntries = append(related.R.PrivateKVSEntries, o)
	}

	return nil
}

// PrivateKVSEntries retrieves all the records using an executor.
func PrivateKVSEntries(mods ...qm.QueryMod) privateKVSEntryQuery {
	mods = append(mods, qm.From("\"private_kvs_entries\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"private_kvs_entries\".*"})
	}

	return privateKVSEntryQuery{q}
}

// FindPrivateKVSEntry retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPrivateKVSEntry(ctx context.Context, exec boil.ContextExecutor, userID string, key string, selectCols ...string) (*PrivateKVSEntry, error) {
	privateKVSEntryObj := &PrivateKVSEntry{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"private_kvs_entries\" where \"user_id\"=$1 AND \"key\"=$2", sel,
	)

	q := queries.Raw(query, userID, key)

	err := q.Bind(ctx, exec, privateKVSEntryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dao: unable to select from private_kvs_entries")
	}

	if err = privateKVSEntryObj.doAfterSelectHooks(ctx, exec); err != nil {
		return privateKVSEntryObj, err
	}

	return privateKVSEntryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PrivateKVSEntry) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dao: no private_kvs_entries provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(privateKVSEntryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	privateKVSEntryInsertCacheMut.RLock()
	cache, cached := privateKVSEntryInsertCache[key]
	privateKVSEntryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			privateKVSEntryAllColumns,
			privateKVSEntryColumnsWithDefault,
			privateKVSEntryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(privateKVSEntryType, privateKVSEntryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(privateKVSEntryType, privateKVSEntryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"private_kvs_entries\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"private_kvs_entries\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dao: unable to insert into private_kvs_entries")
	}

	if !cached {
		privateKVSEntryInsertCacheMut.Lock()
		privateKVSEntryInsertCache[key] = cache
		privateKVSEntryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PrivateKVSEntry.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PrivateKVSEntry) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	privateKVSEntryUpdateCacheMut.RLock()
	cache, cached := privateKVSEntryUpdateCache[key]
	privateKVSEntryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			privateKVSEntryAllColumns,
			privateKVSEntryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dao: unable to update private_kvs_entries, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"private_kvs_entries\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, privateKVSEntryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(privateKVSEntryType, privateKVSEntryMapping, append(wl, privateKVSEntryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update private_kvs_entries row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by update for private_kvs_entries")
	}

	if !cached {
		privateKVSEntryUpdateCacheMut.Lock()
		privateKVSEntryUpdateCache[key] = cache
		privateKVSEntryUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q privateKVSEntryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update all for private_kvs_entries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to retrieve rows affected for private_kvs_entries")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PrivateKVSEntrySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dao: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), privateKVSEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"private_kvs_entries\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, privateKVSEntryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update all in privateKVSEntry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to retrieve rows affected all in update all privateKVSEntry")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PrivateKVSEntry) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dao: no private_kvs_entries provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(privateKVSEntryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	privateKVSEntryUpsertCacheMut.RLock()
	cache, cached := privateKVSEntryUpsertCache[key]
	privateKVSEntryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			privateKVSEntryAllColumns,
			privateKVSEntryColumnsWithDefault,
			privateKVSEntryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			privateKVSEntryAllColumns,
			privateKVSEntryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dao: unable to upsert private_kvs_entries, could not build update column list")
		}

		ret := strmangle.SetComplement(privateKVSEntryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(privateKVSEntryPrimaryKeyColumns) == 0 {
				return errors.New("dao: unable to upsert private_kvs_entries, could not build conflict column list")
			}

			conflict = make([]string, len(privateKVSEntryPrimaryKeyColumns))
			copy(conflict, privateKVSEntryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"private_kvs_entries\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(privateKVSEntryType, privateKVSEntryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(privateKVSEntryType, privateKVSEntryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dao: unable to upsert private_kvs_entries")
	}

	if !cached {
		privateKVSEntryUpsertCacheMut.Lock()
		privateKVSEntryUpsertCache[key] = cache
		privateKVSEntryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PrivateKVSEntry record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PrivateKVSEntry) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dao: no PrivateKVSEntry provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), privateKVSEntryPrimaryKeyMapping)
	sql := "DELETE FROM \"private_kvs_entries\" WHERE \"user_id\"=$1 AND \"key\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete from private_kvs_entries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by delete for private_kvs_entries")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q privateKVSEntryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dao: no privateKVSEntryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete all from private_kvs_entries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by deleteall for private_kvs_entries")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PrivateKVSEntrySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(privateKVSEntryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), privateKVSEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"private_kvs_entries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, privateKVSEntryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete all from privateKVSEntry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by deleteall for private_kvs_entries")
	}

	if len(privateKVSEntryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PrivateKVSEntry) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPrivateKVSEntry(ctx, exec, o.UserID, o.Key)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PrivateKVSEntrySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PrivateKVSEntrySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), privateKVSEntryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"private_kvs_entries\".* FROM \"private_kvs_entries\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, privateKVSEntryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dao: unable to reload all in PrivateKVSEntrySlice")
	}

	*o = slice

	return nil
}

// PrivateKVSEntryExists checks if the PrivateKVSEntry row exists.
func PrivateKVSEntryExists(ctx context.Context, exec boil.ContextExecutor, userID string, key string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"private_kvs_entries\" where \"user_id\"=$1 AND \"key\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, key)
	}
	row := exec.QueryRowContext(ctx, sql, userID, key)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dao: unable to check if private_kvs_entries exists")
	}

	return exists, nil
}

// Exists checks if the PrivateKVSEntry row exists.
func (o *PrivateKVSEntry) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PrivateKVSEntryExists(ctx, exec, o.UserID, o.Key)
}

// /////////////////////////////// BEGIN EXTENSIONS /////////////////////////////////
// Expose table columns
var (
	PrivateKVSEntryAllColumns            = privateKVSEntryAllColumns
	PrivateKVSEntryColumnsWithoutDefault = privateKVSEntryColumnsWithoutDefault
	PrivateKVSEntryColumnsWithDefault    = privateKVSEntryColumnsWithDefault
	PrivateKVSEntryPrimaryKeyColumns     = privateKVSEntryPrimaryKeyColumns
	PrivateKVSEntryGeneratedColumns      = privateKVSEntryGeneratedColumns
)

// InsertAll inserts all rows with the specified column values, using an executor.
func (o PrivateKVSEntrySlice) InsertAll(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var sql string
	vals := []interface{}{}
	for i, row := range o {
		if !boil.TimestampsAreSkipped(ctx) {
			currTime := time.Now().In(boil.GetLocation())
			if row.CreatedAt.IsZero() {
				row.CreatedAt = currTime
			}
			if row.UpdatedAt.IsZero() {
				row.UpdatedAt = currTime
			}
		}

		if err := row.doBeforeInsertHooks(ctx, exec); err != nil {
			return 0, err
		}

		wl, _ := columns.InsertColumnSet(
			privateKVSEntryAllColumns,
			privateKVSEntryColumnsWithDefault,
			privateKVSEntryColumnsWithoutDefault,
			queries.NonZeroDefaultSet(privateKVSEntryColumnsWithDefault, row),
		)
		if i == 0 {
			sql = "INSERT INTO \"private_kvs_entries\" " + "(\"" + strings.Join(wl, "\",\"") + "\")" + " VALUES "
		}
		sql += strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), len(vals)+1, len(wl))
		if i != len(o)-1 {
			sql += ","
		}
		valMapping, err := queries.BindMapping(privateKVSEntryType, privateKVSEntryMapping, wl)
		if err != nil {
			return 0, err
		}

		value := reflect.Indirect(reflect.ValueOf(row))
		vals = append(vals, queries.ValuesFromMapping(value, valMapping)...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, vals)
	}

	result, err := exec.ExecContext(ctx, sql, vals...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to insert all from privateKVSEntry slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by insertall for private_kvs_entries")
	}

	if len(privateKVSEntryAfterInsertHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterInsertHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// UpsertAll inserts or updates all rows
// Currently it doesn't support "NoContext" and "NoRowsAffected"
func (o PrivateKVSEntrySlice) UpsertAll(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	nzDefaults := queries.NonZeroDefaultSet(privateKVSEntryColumnsWithDefault, o[0])

	insert, _ := insertColumns.InsertColumnSet(
		privateKVSEntryAllColumns,
		privateKVSEntryColumnsWithDefault,
		privateKVSEntryColumnsWithoutDefault,
		nzDefaults,
	)
	update := updateColumns.UpdateColumnSet(
		privateKVSEntryAllColumns,
		privateKVSEntryPrimaryKeyColumns,
	)

	if updateOnConflict && len(update) == 0 {
		return 0, errors.New("dao: unable to upsert private_kvs_entries, could not build update column list")
	}

	conflict := conflictColumns
	if len(conflict) == 0 {
		conflict = make([]string, len(privateKVSEntryPrimaryKeyColumns))
		copy(conflict, privateKVSEntryPrimaryKeyColumns)
	}

	buf := strmangle.GetBuffer()
	defer strmangle.PutBuffer(buf)

	columns := "DEFAULT VALUES"
	if len(insert) != 0 {
		columns = fmt.Sprintf("(%s) VALUES %s",
			strings.Join(insert, ", "),
			strmangle.Placeholders(dialect.UseIndexPlaceholders, len(insert)*len(o), 1, len(insert)),
		)
	}

	fmt.Fprintf(
		buf,
		"INSERT INTO %s %s ON CONFLICT ",
		"\"private_kvs_entries\"",
		columns,
	)

	if !updateOnConflict || len(update) == 0 {
		buf.WriteString("DO NOTHING")
	} else {
		buf.WriteByte('(')
		buf.WriteString(strings.Join(conflict, ", "))
		buf.WriteString(") DO UPDATE SET ")

		for i, v := range update {
			if i != 0 {
				buf.WriteByte(',')
			}
			quoted := strmangle.IdentQuote(dialect.LQ, dialect.RQ, v)
			buf.WriteString(quoted)
			buf.WriteString(" = EXCLUDED.")
			buf.WriteString(quoted)
		}
	}

	query := buf.String()
	valueMapping, err := queries.BindMapping(privateKVSEntryType, privateKVSEntryMapping, insert)
	if err != nil {
		return 0, err
	}

	var vals []interface{}
	for _, row := range o {
		if !boil.TimestampsAreSkipped(ctx) {
			currTime := time.Now().In(boil.GetLocation())
			if row.CreatedAt.IsZero() {
				row.CreatedAt = currTime
			}

			row.UpdatedAt = currTime
		}

		if err := row.doBeforeUpsertHooks(ctx, exec); err != nil {
			return 0, err
		}

		value := reflect.Indirect(reflect.ValueOf(row))
		vals = append(vals, queries.ValuesFromMapping(value, valueMapping)...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, vals)
	}

	result, err := exec.ExecContext(ctx, query, vals...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to upsert for private_kvs_entries")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by upsert for private_kvs_entries")
	}

	if len(privateKVSEntryAfterUpsertHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterUpsertHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

///////////////////////////////// END EXTENSIONS /////////////////////////////////
