name: Build Docker Image

on:
  release:
    types: [ published ]
  push:
    branches:
      - develop

jobs:
  api-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: get version
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v5
        with:
          file: ./docker/api-server/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}

  db-migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: get version
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v5
        with:
          file: ./docker/db-migrate/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
